# Generated by Django 4.1.1 on 2022-09-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_tarea_urgente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='urgente',
        ),
    ]
